variables:
  FILES_TO_COMPRESS: "htm html txt text js css md ico svg"

pages:
  image: alpine:latest
  before_script:
    - apk update && apk add gzip brotli
  script:
    - mkdir -p .public .public/css/ .public/css/theme/ .public/js/ .public/js/addOn/
    - cp *.svg index.html script.min.js script.min.js.map .public/
    - cp css/*.min.css .public/css/
    - cp css/theme/* .public/css/theme
    - cp js/addOn/*.js .public/js/addOn/
    - mv .public public
    - for ext in $FILES_TO_COMPRESS; do find public -type f -name "*.$ext" -exec gzip -f -k {} \;; done
    - for ext in $FILES_TO_COMPRESS; do find public -type f -name "*.$ext" -exec brotli -f -k {} \;; done
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
